services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: employee_db_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-^0-_EYRsymZEc7d3}
      POSTGRES_DB: employee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis for Session Storage
  redis:
    image: redis:7-alpine
    container_name: employee_db_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-8ix6Mo7fUmRVno4v}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: